import type { User, Listing, Conversation, Tag, University } from "./types"

export const university: University = {
  id: "uni-1",
  name: "Georgia Institute of Technology",
  emailDomain: "gatech.edu",
}

export const ugaUniversity: University = {
  id: "uni-2",
  name: "University of Georgia",
  emailDomain: "uga.edu",
}

export const tags: Tag[] = [
  { id: "t1", label: "Pickup Only", type: "Preference" },
  { id: "t2", label: "Will Deliver", type: "Preference" },
  { id: "t3", label: "Heavy Item", type: "Custom" },
  { id: "t4", label: "Dorm: North Ave", type: "Dorm" },
  { id: "t5", label: "Dorm: West Village", type: "Dorm" },
  { id: "t6", label: "Dorm: Glenn Hall", type: "Dorm" },
  { id: "t7", label: "OBO", type: "Custom" },
  { id: "t8", label: "Must Go Today", type: "Custom" },
  { id: "t9", label: "Dorm: Myers Hall", type: "Dorm" },
  { id: "t10", label: "Dorm: Brumby Hall", type: "Dorm" },
  { id: "t11", label: "Dorm: Russell Hall", type: "Dorm" },
]

export const currentUser: User = {
  id: "u1",
  email: "alex.rivera@gatech.edu",
  name: "Alex Rivera",
  avatarUrl: "",
  university,
  tags: [tags[3], tags[1]],
  bio: "CS major, graduating in May. Clearing out my dorm!",
  createdAt: "2025-08-20T00:00:00Z",
}

export const users: User[] = [
  currentUser,
  {
    id: "u2",
    email: "jordan.lee@gatech.edu",
    name: "Jordan Lee",
    avatarUrl: "",
    university,
    tags: [tags[4], tags[0]],
    bio: "Pre-med student. Love finding free stuff on campus.",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "u3",
    email: "sam.patel@gatech.edu",
    name: "Sam Patel",
    avatarUrl: "",
    university,
    tags: [tags[5], tags[1]],
    bio: "Engineering student. Always looking for monitors and tech.",
    createdAt: "2025-09-15T00:00:00Z",
  },
  {
    id: "u4",
    email: "maya.chen@gatech.edu",
    name: "Maya Chen",
    avatarUrl: "",
    university,
    tags: [tags[3], tags[0]],
    bio: "Art major. Downsizing my collection.",
    createdAt: "2025-10-01T00:00:00Z",
  },
]

export const ugaUsers: User[] = [
  {
    id: "u5",
    email: "taylor.brooks@uga.edu",
    name: "Taylor Brooks",
    avatarUrl: "",
    university: ugaUniversity,
    tags: [tags[8], tags[1]],
    bio: "Junior at UGA. Clearing out my dorm before summer!",
    createdAt: "2025-08-15T00:00:00Z",
  },
  {
    id: "u6",
    email: "morgan.hayes@uga.edu",
    name: "Morgan Hayes",
    avatarUrl: "",
    university: ugaUniversity,
    tags: [tags[9], tags[0]],
    bio: "Biology major, dog lover. Go Dawgs!",
    createdAt: "2025-09-10T00:00:00Z",
  },
  {
    id: "u7",
    email: "casey.wright@uga.edu",
    name: "Casey Wright",
    avatarUrl: "",
    university: ugaUniversity,
    tags: [tags[10], tags[1]],
    bio: "Journalism student. Downsizing before I move off campus.",
    createdAt: "2025-10-05T00:00:00Z",
  },
]

// Combined users array for seeding
users.push(...ugaUsers)

export const listings: Listing[] = [
  {
    id: "l1",
    title: "Blue Futon Couch",
    description: "Super comfy futon, folds flat into a bed. Some minor wear on the armrests but still in great condition. Perfect for a dorm or apartment living room. I'm moving out and can't take it with me.",
    images: ["/listings/couch.jpg"],
    category: "Furniture",
    condition: "Good",
    tags: [tags[0], tags[2]],
    status: "Available",
    location: "Outside North Ave lobby",
    seller: users[0],
    claimedBy: null,
    createdAt: "2026-01-28T14:30:00Z",
    expiresAt: "2026-02-27T14:30:00Z",
  },
  {
    id: "l2",
    title: "Calculus & Biology Textbooks",
    description: "Bundle of 3 textbooks: Calculus Early Transcendentals (8th ed), Campbell Biology (12th ed), and Organic Chemistry (5th ed). Some highlighting but pages are clean. Save hundreds on these!",
    images: ["/listings/textbooks.jpg"],
    category: "Textbooks",
    condition: "Like New",
    tags: [tags[1]],
    status: "Available",
    location: "Crosland Tower front desk",
    seller: users[1],
    claimedBy: null,
    createdAt: "2026-02-01T09:00:00Z",
    expiresAt: "2026-03-03T09:00:00Z",
  },
  {
    id: "l3",
    title: "Modern Desk Lamp",
    description: "LED desk lamp with adjustable brightness and color temperature. USB charging port on the base. Used for one semester, works perfectly.",
    images: ["/listings/lamp.jpg"],
    category: "Other",
    condition: "Like New",
    tags: [tags[0]],
    status: "Available",
    location: "Glenn Hall Room 412",
    seller: users[2],
    claimedBy: null,
    createdAt: "2026-02-03T16:45:00Z",
    expiresAt: "2026-03-05T16:45:00Z",
  },
  {
    id: "l4",
    title: "Mechanical Keyboard",
    description: "Cherry MX Blue switches, full RGB lighting. Used for about a year. All keys work perfectly. Comes with original USB-C cable and keycap puller.",
    images: ["/listings/keyboard.jpg"],
    category: "Electronics",
    condition: "Good",
    tags: [tags[0], tags[7]],
    status: "Available",
    location: "Klaus Building lobby",
    seller: users[0],
    claimedBy: null,
    createdAt: "2026-02-04T11:20:00Z",
    expiresAt: "2026-03-06T11:20:00Z",
  },
  {
    id: "l5",
    title: "Denim Jacket - Size M",
    description: "Classic denim jacket, medium size. Barely worn, just not my style anymore. Great for Austin spring weather.",
    images: ["/listings/jacket.jpg"],
    category: "Clothing",
    condition: "Like New",
    tags: [tags[1]],
    status: "Claimed",
    location: "West Village mailroom",
    seller: users[3],
    claimedBy: users[1],
    createdAt: "2026-01-25T08:00:00Z",
    expiresAt: "2026-02-24T08:00:00Z",
  },
  {
    id: "l6",
    title: "Countertop Blender",
    description: "NutriBullet-style personal blender. Makes great smoothies. Comes with two cups and lids. Used for one semester.",
    images: ["/listings/blender.jpg"],
    category: "Kitchen",
    condition: "Good",
    tags: [tags[0]],
    status: "Available",
    location: "North Ave kitchen area",
    seller: users[1],
    claimedBy: null,
    createdAt: "2026-02-05T13:10:00Z",
    expiresAt: "2026-03-07T13:10:00Z",
  },
  {
    id: "l7",
    title: '24" Dell Monitor',
    description: "Dell SE2422HX 24-inch monitor. 1080p, 75Hz. HDMI cable included. Perfect second monitor for your setup. Minor scratch on the bezel, screen is flawless.",
    images: ["/listings/monitor.jpg"],
    category: "Electronics",
    condition: "Good",
    tags: [tags[0], tags[2]],
    status: "Available",
    location: "CULC building entrance",
    seller: users[2],
    claimedBy: null,
    createdAt: "2026-02-06T10:00:00Z",
    expiresAt: "2026-03-08T10:00:00Z",
  },
  {
    id: "l8",
    title: "Small Wooden Bookshelf",
    description: "3-shelf bookshelf, about 3 feet tall. Solid wood, not particle board. Fits perfectly in a dorm room corner. Disassembles for easy transport.",
    images: ["/listings/bookshelf.jpg"],
    category: "Furniture",
    condition: "Fair",
    tags: [tags[0], tags[2]],
    status: "Available",
    location: "Outside Glenn Hall",
    seller: users[3],
    claimedBy: null,
    createdAt: "2026-02-02T15:30:00Z",
    expiresAt: "2026-03-04T15:30:00Z",
  },

  // --- UGA Listings ---
  {
    id: "l9",
    title: "Mini Fridge - Great Condition",
    description: "Compact mini fridge, perfect for a dorm room. Fits under most desks. Has a small freezer compartment at the top. Used for two semesters, works perfectly. Just cleaned it out.",
    images: ["/listings/fridge.jpg"],
    category: "Kitchen",
    condition: "Good",
    tags: [tags[0], tags[2]],
    status: "Available",
    location: "Myers Hall lobby",
    seller: ugaUsers[0],
    claimedBy: null,
    createdAt: "2026-01-30T10:00:00Z",
    expiresAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "l10",
    title: "Psychology & Sociology Textbooks",
    description: "Intro to Psychology (Myers, 13th ed) and Principles of Sociology (Giddens). Both in great shape, minimal highlighting. Perfect for freshmen taking core classes.",
    images: ["/listings/psych-textbooks.jpg"],
    category: "Textbooks",
    condition: "Like New",
    tags: [tags[1]],
    status: "Available",
    location: "Tate Student Center info desk",
    seller: ugaUsers[1],
    claimedBy: null,
    createdAt: "2026-02-01T11:30:00Z",
    expiresAt: "2026-03-03T11:30:00Z",
  },
  {
    id: "l11",
    title: "Yoga Mat + Resistance Bands Set",
    description: "Thick yoga mat (purple) and a set of 5 resistance bands with different tensions. Used for a semester of workout classes. Mat is clean and bands are in perfect shape.",
    images: ["/listings/yoga-mat.jpg"],
    category: "Other",
    condition: "Good",
    tags: [tags[0]],
    status: "Available",
    location: "Ramsey Student Center entrance",
    seller: ugaUsers[2],
    claimedBy: null,
    createdAt: "2026-02-03T09:15:00Z",
    expiresAt: "2026-03-05T09:15:00Z",
  },
  {
    id: "l12",
    title: "Bean Bag Chair - Red",
    description: "Big comfy bean bag chair, red faux leather. Great for gaming or just chilling in your room. Cover is removable and washable. Barely used.",
    images: ["/listings/beanbag.jpg"],
    category: "Furniture",
    condition: "Like New",
    tags: [tags[0], tags[2]],
    status: "Available",
    location: "Brumby Hall courtyard",
    seller: ugaUsers[0],
    claimedBy: null,
    createdAt: "2026-02-04T14:00:00Z",
    expiresAt: "2026-03-06T14:00:00Z",
  },
  {
    id: "l13",
    title: "Bluetooth Speaker - JBL Clip",
    description: "JBL Clip 3 portable speaker, teal color. Clips onto a backpack. Great sound for its size. Battery holds charge well. Comes with charging cable.",
    images: ["/listings/speaker.jpg"],
    category: "Electronics",
    condition: "Good",
    tags: [tags[1]],
    status: "Available",
    location: "Bolton Dining Commons",
    seller: ugaUsers[1],
    claimedBy: null,
    createdAt: "2026-02-05T16:45:00Z",
    expiresAt: "2026-03-07T16:45:00Z",
  },
  {
    id: "l14",
    title: "UGA Hoodie - Size L",
    description: "Classic red UGA hoodie, size large. Worn a handful of times, no stains or damage. Super cozy and warm. Go Dawgs!",
    images: ["/listings/uga-hoodie.jpg"],
    category: "Clothing",
    condition: "Like New",
    tags: [tags[1]],
    status: "Claimed",
    location: "Russell Hall entrance",
    seller: ugaUsers[2],
    claimedBy: ugaUsers[0],
    createdAt: "2026-01-27T08:30:00Z",
    expiresAt: "2026-02-26T08:30:00Z",
  },
  {
    id: "l15",
    title: "Desk Fan - Clip-on",
    description: "Small clip-on desk fan with 3 speed settings. USB powered so you can plug it into your laptop. Quiet and surprisingly powerful. Great for hot dorm rooms.",
    images: ["/listings/desk-fan.jpg"],
    category: "Electronics",
    condition: "Good",
    tags: [tags[0], tags[7]],
    status: "Available",
    location: "Science Library front steps",
    seller: ugaUsers[0],
    claimedBy: null,
    createdAt: "2026-02-06T12:00:00Z",
    expiresAt: "2026-03-08T12:00:00Z",
  },
]

export const conversations: Conversation[] = [
  {
    id: "c1",
    listing: listings[0],
    participants: [users[0], users[1]],
    messages: [
      {
        id: "m1",
        conversationId: "c1",
        sender: users[1],
        body: "Hey! Is the futon still available? I can pick it up today.",
        attachments: [],
        read: true,
        createdAt: "2026-02-05T10:00:00Z",
      },
      {
        id: "m2",
        conversationId: "c1",
        sender: users[0],
        body: "Yes it is! I'll be at North Ave until 5pm today. Just come to the lobby and text me when you're here.",
        attachments: [],
        read: true,
        createdAt: "2026-02-05T10:05:00Z",
      },
      {
        id: "m3",
        conversationId: "c1",
        sender: users[1],
        body: "Perfect, I'll be there around 3. Do you have a dolly or should I bring one?",
        attachments: [],
        read: false,
        createdAt: "2026-02-05T10:10:00Z",
      },
    ],
    lastMessage: null,
  },
  {
    id: "c2",
    listing: listings[3],
    participants: [users[0], users[2]],
    messages: [
      {
        id: "m4",
        conversationId: "c2",
        sender: users[2],
        body: "What switch type is the keyboard? And does it come with a wrist rest?",
        attachments: [],
        read: true,
        createdAt: "2026-02-05T14:00:00Z",
      },
      {
        id: "m5",
        conversationId: "c2",
        sender: users[0],
        body: "Cherry MX Blues - they're clicky! No wrist rest unfortunately, just the board and cable.",
        attachments: [],
        read: true,
        createdAt: "2026-02-05T14:15:00Z",
      },
    ],
    lastMessage: null,
  },
  {
    id: "c3",
    listing: listings[4],
    participants: [users[3], users[1]],
    messages: [
      {
        id: "m6",
        conversationId: "c3",
        sender: users[1],
        body: "Love the jacket! Is it still available?",
        attachments: [],
        read: true,
        createdAt: "2026-01-26T09:00:00Z",
      },
      {
        id: "m7",
        conversationId: "c3",
        sender: users[3],
        body: "Yes! Want to pick it up from West Village mailroom? I can leave it there for you.",
        attachments: [],
        read: true,
        createdAt: "2026-01-26T09:30:00Z",
      },
      {
        id: "m8",
        conversationId: "c3",
        sender: users[1],
        body: "That would be amazing, thank you! I'll grab it this afternoon.",
        attachments: [],
        read: true,
        createdAt: "2026-01-26T10:00:00Z",
      },
    ],
    lastMessage: null,
  },
]

// Set lastMessage references
conversations.forEach((c) => {
  c.lastMessage = c.messages[c.messages.length - 1] || null
})

export const categories = [
  "All",
  "Furniture",
  "Textbooks",
  "Electronics",
  "Clothing",
  "Kitchen",
  "Other",
] as const

export const conditions = ["New", "Like New", "Good", "Fair"] as const
